# Generated by Django 2.2.5 on 2019-09-17 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonatorsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonatsSourcesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonationsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.IntegerField(blank=True, null=True)),
                ('donat_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='donat.DonatsSourcesData')),
                ('donator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='donat.DonatorsData')),
            ],
        ),
    ]
