# Generated by Django 2.2.5 on 2019-09-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
